version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    target-branch: develop
    commit-message:
      prefix: ci

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
    target-branch: develop
    commit-message:
      prefix: fix
