geolVersion: "2"
# cuelang file : https://github.com/opt-nc/geol/blob/main/geol_stack.cue
app_name: Tower Deploy Action
app_id: tower-deploy-action

stack:
  - name: node
    version: "24"
    id_eol: nodejs
