# action.yml
name: 'Deploy with Tower Ansible'
description: 'Deploy application thanks Tower Ansible'
branding :
  icon : 'zap'
  color : 'red'

inputs:
  extravars_template_filename:
    description: "Fichier yaml templaté contenant les extra_vars"
    required: true
    default: 'src/main/resources/tower_extra_vars_template.yml'
  vars:
    description: "Liste des variables (json) qui seront utilisées dans le template"
    required: true
  asset_url:
    description: "Url de l'asset à déployer (image_url ou asset_url doit être spécifié)"
    required: false
  image_url:
    description: "Nom de l'image Docker (image_url ou asset_url doit être spécifié)"
    required: false
  tower_template_id:
    description: "Identifiant du template Tower"
    required: true
  tower_url:
    description: "Url de Tower"
    required: true
  tower_user:
    description: "Identifiant utilisé pour le déploiement"
    required: true
  tower_password:
    description: "Mot de passe utilisé pour le déploiement"
    required: true
  tower_timeout:
    description: "Délai avant coupure de la connexion"
    required: true
    default: "300"

runs:
  using: 'node16'
  main: 'dist/index.js'
