# action.yml
name: 'Deploy with Tower Ansible'
description: 'Deploy application thanks Tower Ansible'
branding :
  icon : 'zap'
  color : 'red'

inputs:
  extravars_template_filename:
    description: "Fichier yaml templaté contenant les extra_vars"
    required: true
    default: 'src/main/resources/tower_extra_vars_template.yml'
  vars:
    description: "Liste des variables (json) qui seront utilisées dans le template"
    required: true
  asset_url:
    description: "Url de l'asset à déployer"
    required: true
  tower_template_id:
    description: "Identifiant du template Tower"
    required: true
  tower_url:
    description: "Url de Tower"
    required: true
  tower_user:
    description: "Identifiant utilisé pour le déploiement"
    required: true
  tower_password:
    description: "Mot de passe utilisé pour le déploiement"
    required: true
  tower_timeout:
    description: "Délai avant coupure de la connexion"
    required: true
    default: "300"

runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    EXTRA_VARS_TEMPLATE_FILENAME: ${{ env.GITHUB_WORKSPACE }}${{ inputs.extravars_template_filename }}
    ARTIFACT_URL: ${{ inputs.asset_url }}
    SECRETS_CONTEXT: ${{ inputs.vars }} 
    TOWER_TEMPLATE_ID: ${{ inputs.tower_template_id }}
    EXTRA_VARS_FILE: ${{GITHUB_WORKSPACE}}/tmp_extra_vars.txt
    TOWER_URL: ${{ inputs.tower_url }}
    TOWER_USER: ${{ inputs.tower_user }}
    TOWER_PASSWORD: ${{ inputs.tower_password }}
    TOWER_TIMEOUT: ${{ inputs.tower_timeout }}


